#!/bin/bash
if test -f ~/.imgur.sh; then
  source ~/.imgur.sh
else
  echo 'Cant find ~/.imgur.sh'
  exit 1
fi

scrot -s "shot.png" 
json=$(curl -s --request POST --url https://api.imgur.com/3/image \
  --header "authorization: Client-ID $client_id" \
  --header "content-type: multipart/form-data;" -F "image=@shot.png")

success=$(echo $json | jq '.success')

if [ "$success" == "true" ]; then
  link=$(echo $json | jq '.data.link' | tr -d \")

  echo $link | xsel --clipboard
  # Open in browser
  #gio open $link
  # Notify upload
  notify-send "Image uploaded to $link" -i "viewimage"
fi

rm "shot.png"
