#!/usr/bin/bash
# Layouts as parameters $1 and $2

current_layout=$(setxkbmap -query | grep -i layout | cut -d ' ' -f 6)


if [ -n "$1" ];then
    if [ $current_layout = "$1" ]; then
        setxkbmap "$2"
    else
        setxkbmap "$1"
    fi
else
    setxkbmap -option "caps:swapescape"
fi
