#!/bin/sh

compton --daemon --config $HOME/.config/compton/config &

tint2 -c $HOME/.config/tint2/tint2rc &

dunst &

xset r rate 200 30 &

nitrogen --restore &

nm-applet &
# blueman-applet &
greenclip daemon &
redshift -b 0.95:0.9 &

# vim: set ft=sh:
